export default function BentoGrid() {
  return (
    <>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
      <div>Bento grid component</div>
    </>
  );
}
